#!/usr/bin/env python3
"""Export a deterministic direct-copy layout for SKILL.md-only hosts."""

from __future__ import annotations

import argparse
from pathlib import Path
import shutil
import sys


ROOT = Path(__file__).resolve().parents[1]
IGNORE = shutil.ignore_patterns("__pycache__", "*.pyc", ".DS_Store")
MARKER = ".naval-direct-install-bundle"


def fail(message: str) -> None:
    print(f"direct install export failed: {message}", file=sys.stderr)
    raise SystemExit(1)


def safe_output_path(path: Path, force: bool) -> Path:
    output = path.expanduser().resolve()
    root = ROOT.resolve()
    home = Path.home().resolve()
    blocked = {Path("/").resolve(), home, root, root.parent}
    if output in blocked:
        fail(f"refusing dangerous output path: {output}")
    if root.is_relative_to(output):
        fail("output path cannot contain the source checkout")
    if output.exists() and any(output.iterdir()):
        if not force:
            fail(f"{output} exists and is not empty; choose an empty directory or pass --force")
        if not (output / MARKER).is_file():
            fail(f"refusing to replace non-generated directory without {MARKER}: {output}")
        shutil.rmtree(output)
    output.mkdir(parents=True, exist_ok=True)
    (output / MARKER).write_text("generated by scripts/export_direct_install.py\n", encoding="utf-8")
    return output


def copy_tree(source: Path, dest: Path) -> None:
    shutil.copytree(source, dest, ignore=IGNORE)


def write_readme(output: Path, skill_count: int) -> None:
    (output / "README.md").write_text(
        f"""# Naval Direct Install Bundle

This folder is a direct-copy bundle for SKILL.md-only hosts.

It contains:

- `skills/` with {skill_count} `n-*` Naval skills.
- `references/` with the shared files those skills load through `../../references/...`.

Keep `skills/` and `references/` as siblings. Do not copy only the individual skill folders unless the target host already has this exact sibling `references/` folder.

Validate from the source checkout:

```bash
python3 scripts/validate_direct_install.py --agent-root {output}
```
""",
        encoding="utf-8",
    )


def export_bundle(output: Path, force: bool) -> int:
    skills = sorted((ROOT / "skills").glob("n-*"))
    if not skills:
        fail("no source skills found")
    references = ROOT / "references"
    if not references.exists():
        fail("source references folder missing")

    output = safe_output_path(output, force)
    skills_dest = output / "skills"
    refs_dest = output / "references"
    skills_dest.mkdir()
    for source in skills:
        copy_tree(source, skills_dest / source.name)
    copy_tree(references, refs_dest)
    write_readme(output, len(skills))
    print(f"Exported direct install bundle: {output}")
    print(f"Skills: {len(skills)}")
    print("Next: python3 scripts/validate_direct_install.py --agent-root " + str(output))
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Empty directory to create with sibling skills/ and references/ folders.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace the output directory if it already exists and is non-empty.",
    )
    args = parser.parse_args()
    return export_bundle(args.output, args.force)


if __name__ == "__main__":
    raise SystemExit(main())
